spring.application.name=lapwise-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/lapwise
spring.datasource.username=lapwise
spring.datasource.password=lapwise

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
